#!/usr/bin/perl -w
#
#  Simple script to request a lot of URLs and compare any received
# HTTP-Redirection requests against that we expected.
#
#  This is used to test Steve's personal server, but might be useful
# for others.
#
# Steve
# --
#



use strict;
use warnings;

use LWP::UserAgent;



#
#  Failure count + Test count
#
my $fail  = 0;
my $count = 0;


while ( my $line = <DATA> )
{
    chomp($line);

    next if ( !length($line) || $line =~ /^#/ );
    if ( $line =~ /([^ \t]+)([ \t]+)([^ \t]+)/ )
    {
        my $from     = $1;
        my $to       = $3;
        my $response = getRedirect($from);

        if ( defined $response )
        {
            if ( $response ne $to )
            {
                print "ERR - $from redirected to $to not $response\n";
                $fail += 1;
            }
        }
        else
        {
            $fail += 1;
            print "ERR - Failed to find redirection header for $from\n";
        }

        $count += 1;
    }
}

my $ok = $count - $fail;

print "Tests completed: [$ok/$count]\n";
print "Failed tests   : $fail\n" if ($fail);



sub getRedirect
{
    my ($url) = (@_);

    #
    #  Create a user-agent, ensuring we don't follow redirects.
    #
    my $agent = LWP::UserAgent->new( max_redirect => 0 );

    #
    #  Get the response
    #
    my $response = $agent->get($url);
    return undef if ( !defined($response ) );

    #
    #  Find the headers
    #
    my $headers = $response->headers();
    return undef if ( !defined($headers ) );

    #
    #  Return the location from the headers, if found.
    #
    return ( $headers->{ 'location' } || undef );

}





__DATA__

#
#  Blogspam.net
#
http://api.blogspam.net/  http://blogspam.net/api
http://test.blogspam.net/ http://blogspam.net/
http://www.blogspam.net/  http://blogspam.net/

#
#  KVM Hosting
#
http://www.kvm-hosting.com/ http://kvm-hosting.org/
http://www.kvm-hosting.org/ http://kvm-hosting.org/
http://www.kvm-hosting.net/ http://kvm-hosting.org/

http://kvm-hosting.com/     http://kvm-hosting.org/
http://kvm-hosting.net/     http://kvm-hosting.org/

#
#  Mail-Scanning
#
http://mail-scanning.com/      http://book.mail-scanning.com/
http://www.mail-scanning.com/  http://book.mail-scanning.com/

#
#  Repository
#
http://chronicle.repository.steve.org.uk/ http://repository.steve.org.uk/cgi-bin/hgwebdir.cgi/chronicle/
http://mybin.repository.steve.org.uk/file http://repository.steve.org.uk/cgi-bin/hgwebdir.cgi/mybin/file
http://itag.repository.steve.org.uk/ http://repository.steve.org.uk/cgi-bin/hgwebdir.cgi/itag/
http://foof.repository.steve.org.uk/ http://repository.steve.org.uk/cgi-bin/hgwebdir.cgi/foof/


#
#  Steve.org.uk
#
http://steve.org.uk/          http://www.steve.org.uk/

#
#  Stolen-Souls
#
http://www.stolen-souls.com/  http://stolen-souls.com/

#
#  Stored-Online
#
http://www.stored-online.com/ http://stored-online.com/


#
#  Xen-Hosting
#
http://xen-hosting.org/      http://kvm-hosting.org/
http://www.xen-hosting.org/  http://kvm-hosting.org/
http://xen-hosting.net/      http://kvm-hosting.org/
http://www.xen-hosting.net/  http://kvm-hosting.org/

